student_name = input("Enter student name: ")
student_id = input("Enter student ID: ")
department = input("Enter department: ")
university = input("Enter university: ")
phone = input("Enter phone number: ")
year = int(input("Enter year: "))
print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name: {student_name:<25}|")
print(f"| ID: {student_id:<27}|")
print(f"| Department: {department:<19}|")
print(f"| Year: {year:<26}|")
print(f"| University: {university:<19}|")
print(f"| Phone: {phone:<25}|")
print("+--------------------------------+")